"""added user table

Revision ID: 31660cb80d48
Revises: 
Create Date: 2021-09-27 10:55:01.448535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31660cb80d48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
