"""added user table

Revision ID: df8f1c0e949d
Revises: 31660cb80d48
Create Date: 2021-09-27 10:59:43.669054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8f1c0e949d'
down_revision = '31660cb80d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
